apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.composer.service: composer
  name: composer
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.composer.service: composer
status:
  loadBalancer: {}
