apiVersion: v1
kind: Service
metadata:
  labels:
    io.composer.service: membersrvc
  name: membersrvc
spec:
  ports:
  - name: "7054"
    port: 7054
    targetPort: 7054
  selector:
    io.composer.service: membersrvc
status:
  loadBalancer: {}
