apiVersion: v1
kind: Service
metadata:
  labels:
    io.composer.service: vp0
  name: vp0
spec:
  ports:
  - name: "7050"
    port: 7050
    targetPort: 7050
  - name: "7051"
    port: 7051
    targetPort: 7051
  - name: "7052"
    port: 7052
    targetPort: 7052
  - name: "7053"
    port: 7053
    targetPort: 7053
  selector:
    io.composer.service: vp0
status:
  loadBalancer: {}
