apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.composer.service: orderer0
  name: orderer0
spec:
  ports:
  - name: "7050"
    port: 7050
    targetPort: 7050
  selector:
    io.composer.service: orderer0
status:
  loadBalancer: {}
