apiVersion: v1
kind: DeploymentConfig
metadata:
  name: orderer0
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.composer.service: orderer0
    spec:
      containers:
      - args:
        - orderer
        env:
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value: /etc/hyperledger/configtx/twoorgs.orderer.block
        - name: ORDERER_GENERAL_LOCALMSPID
          value: OrdererMSP
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /etc/hyperledger/msp/orderer
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "false"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: /etc/hyperledger/tls/orderer/key.pem
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: /etc/hyperledger/tls/orderer/cert.pem
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: '[/etc/hyperledger/tls/orderer/ca-cert.pem, /etc/hyperledger/tls/peers/peer0/ca-cert.pem,
            /etc/hyperledger/tls/peers/peer2/ca-cert.pem]'
        image: hyperledger/fabric-orderer:x86_64-1.0.0-alpha
        name: orderer0
        ports:
        - containerPort: 7050
        resources: {}
        volumeMounts:
        - mountPath: /etc/hyperledger/configtx
          name: orderer0-claim0
        - mountPath: /etc/hyperledger/msp/orderer
          name: orderer0-claim1
      restartPolicy: Always
      volumes:
      - name: orderer0-claim0
        emptyDir: {}
      - name: orderer0-claim1
        emptyDir: {}
status: {}
