apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.composer.service: peer1
  name: peer1
spec:
  ports:
  - name: "7056"
    port: 7056
    targetPort: 7051
  - name: "7058"
    port: 7058
    targetPort: 7053
  selector:
    io.composer.service: peer1
status:
  loadBalancer: {}
